databases:
  - name: ndvidb
    plan: free
    databaseName: ndvi
    user: ndvi

services:
  - type: web
    plan: free
    name: ndvi
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn ndvi.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ndvidb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
