databases:
  - name: linkydb
    plan: free
    databaseName: linky
    user: linky

services:
  - type: web
    plan: free
    name: linky
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn linky_api.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: linkydb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
