# Generated by Django 5.0.2 on 2024-02-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ndvi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('polygon', models.TextField()),
                ('ndvi', models.FloatField(default=0.0)),
                ('cvs_data', models.TextField(default='')),
                ('start_date', models.TextField()),
                ('end_date', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
