# Generated by Django 5.0.2 on 2024-02-26 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ndvi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ndvi',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='ndvi',
            name='start_date',
        ),
    ]
